const nowIso = () => new Date().toISOString();

export function createWebhookFixture(type: string, overrides: Record<string, unknown> = {}): Record<string, unknown> {
  const event = {
    id: `evt_${Date.now()}`,
    object: "event",
    created: nowIso(),
    type,
    data: defaultDataForType(type),
    ...overrides,
  };

  return event;
}

function defaultDataForType(type: string): Record<string, unknown> {
  if (type.startsWith("session.")) {
    return {
      sessionId: "sess_test_123",
      status: "complete",
      paymentStatus: "paid",
      originalCurrency: "USD",
      amountTotal: 1999,
      merchantReferenceId: "order_test_123",
      customer: {
        customerId: "cus_test_123",
        email: "test@example.com",
      },
    };
  }

  if (type.startsWith("order.")) {
    return {
      orderId: "ord_test_123",
      status: type.endsWith("succeeded") ? "succeeded" : "created",
      amount: 1999,
      currency: "USD",
      merchantReferenceId: "order_test_123",
      sessionId: "sess_test_123",
    };
  }

  if (type.startsWith("subscription.")) {
    return {
      subscriptionId: "sub_test_123",
      status: "activated",
      productId: "prd_test_123",
      priceId: "price_test_123",
      customerId: "cus_test_123",
    };
  }

  if (type.startsWith("invoice.")) {
    return {
      invoiceId: "inv_test_123",
      status: type.endsWith("paid") ? "paid" : "open",
      amount: 1999,
      currency: "USD",
      subscriptionId: "sub_test_123",
    };
  }

  return {
    note: "Generated by clink-dev-cli local webhook simulation",
  };
}

