export const WEBHOOK_FIXTURE_TYPES = [
  "session.complete",
  "session.expired",
  "order.created",
  "order.succeeded",
  "order.failed",
  "subscription.created",
  "subscription.activated",
  "subscription.past_due",
  "invoice.open",
  "invoice.paid",
  "invoice.void",
] as const;

type WebhookFixtureType = (typeof WEBHOOK_FIXTURE_TYPES)[number];

const FIXTURE_EVENT_CREATED = "2025-01-15T12:00:00.000Z";
const CHECKOUT_CREATED_AT = "2025-01-15T11:45:00.000Z";
const CHECKOUT_EXPIRES_AT = "2025-01-15T12:45:00.000Z";
const CHECKOUT_EXPIRED_AT = "2025-01-15T12:45:00.000Z";
const ORDER_CREATED_AT = "2025-01-15T11:50:00.000Z";
const ORDER_PAID_AT = "2025-01-15T11:55:00.000Z";
const ORDER_CREATED_TIME = Date.parse(ORDER_CREATED_AT);
const ORDER_PAYMENT_TIME = Date.parse(ORDER_PAID_AT);
const SUBSCRIPTION_CREATED_AT = "2025-01-15T11:56:00.000Z";
const SUBSCRIPTION_ACTIVATED_AT = "2025-01-15T11:57:00.000Z";
const CURRENT_PERIOD_START = "2025-01-15T00:00:00.000Z";
const CURRENT_PERIOD_END = "2025-02-15T00:00:00.000Z";
const INVOICE_CREATED_AT = "2025-01-15T11:58:00.000Z";
const INVOICE_DUE_AT = "2025-01-22T00:00:00.000Z";
const INVOICE_PAID_AT = "2025-01-15T12:00:00.000Z";
const INVOICE_VOIDED_AT = "2025-01-16T12:00:00.000Z";

export function createWebhookFixture(type: string, overrides: Record<string, unknown> = {}): Record<string, unknown> {
  const event = {
    id: fixtureEventId(type),
    object: "event",
    created: FIXTURE_EVENT_CREATED,
    livemode: false,
    type,
    data: defaultDataForType(type),
    ...overrides,
  };

  return event;
}

function defaultDataForType(type: string): Record<string, unknown> {
  const builder = fixtureBuilders[type as WebhookFixtureType];
  if (builder) return builder();

  return {
    note: "Generated by clink-dev-cli local webhook simulation",
  };
}

const fixtureBuilders: Record<WebhookFixtureType, () => Record<string, unknown>> = {
  "session.complete": () =>
    sessionFixture({
      status: "completed",
      paymentStatus: "paid",
      orderId: "ord_test_123",
      expiresAt: CHECKOUT_EXPIRES_AT,
    }),
  "session.expired": () =>
    sessionFixture({
      status: "expired",
      paymentStatus: "unpaid",
      orderId: null,
      expiresAt: CHECKOUT_EXPIRED_AT,
    }),
  "order.created": () =>
    orderFixture({
      status: "pending",
      paymentTime: null,
      paymentExecutionDetails: [],
    }),
  "order.succeeded": () =>
    orderFixture({
      status: "success",
      paymentTime: ORDER_PAYMENT_TIME,
      paymentExecutionDetails: [],
    }),
  "order.failed": () =>
    orderFixture({
      status: "failed",
      paymentTime: ORDER_PAYMENT_TIME,
      paymentExecutionDetails: [
        {
          channelCode: "CARD",
          originalFailureCode: "card_declined",
          originalFailureMessage: "The payment method was declined in the local fixture.",
        },
      ],
    }),
  "subscription.created": () =>
    subscriptionFixture({
      status: "created",
      activatedAt: null,
      pastDueSince: null,
    }),
  "subscription.activated": () =>
    subscriptionFixture({
      status: "activated",
      activatedAt: SUBSCRIPTION_ACTIVATED_AT,
      pastDueSince: null,
    }),
  "subscription.past_due": () =>
    subscriptionFixture({
      status: "past_due",
      activatedAt: SUBSCRIPTION_ACTIVATED_AT,
      pastDueSince: "2025-02-16T00:00:00.000Z",
    }),
  "invoice.open": () =>
    invoiceFixture({
      status: "open",
      amountDue: 1999,
      amountPaid: 0,
      paidAt: null,
      voidedAt: null,
    }),
  "invoice.paid": () =>
    invoiceFixture({
      status: "paid",
      amountDue: 1999,
      amountPaid: 1999,
      paidAt: INVOICE_PAID_AT,
      voidedAt: null,
    }),
  "invoice.void": () =>
    invoiceFixture({
      status: "void",
      amountDue: 1999,
      amountPaid: 0,
      paidAt: null,
      voidedAt: INVOICE_VOIDED_AT,
    }),
};

function fixtureEventId(type: string): string {
  return `evt_${type.replace(/[^a-z0-9]+/gi, "_")}_test`;
}

function baseCustomer(): Record<string, unknown> {
  return {
    customerId: "cus_test_123",
    email: "test@example.com",
    name: "Test Customer",
  };
}

function baseLineItems(): Record<string, unknown>[] {
  return [
    {
      productId: "prd_test_123",
      priceId: "price_test_123",
      description: "Local webhook test plan",
      quantity: 1,
      unitAmount: 1999,
      amountTotal: 1999,
    },
  ];
}

function basePriceDataList(): Record<string, unknown>[] {
  return [
    {
      name: "Local webhook test plan",
      quantity: 1,
      unitAmount: 1999,
      currency: "USD",
      imageUrl: "https://merchant.example/assets/local-webhook-test.png",
    },
  ];
}

function baseMetadata(): Record<string, unknown> {
  return {
    environment: "local",
    source: "clink-dev-cli",
  };
}

function sessionFixture(values: {
  status: string;
  paymentStatus: string;
  orderId: string | null;
  expiresAt: string;
}): Record<string, unknown> {
  return {
    sessionId: "sess_test_123",
    token: "tok_test_123",
    status: values.status,
    paymentStatus: values.paymentStatus,
    originalCurrency: "USD",
    paymentCurrency: "USD",
    amountSubtotal: 1999,
    amountTotal: 1999,
    subscriptionId: null,
    invoiceId: null,
    orderId: values.orderId,
    merchantReferenceId: "order_test_123",
    customer: baseCustomer(),
    locale: "en-US",
    uiMode: "hostedPage",
    returnUrl: null,
    successUrl: "https://merchant.example/success",
    cancelUrl: "https://merchant.example/cancel",
    created: CHECKOUT_CREATED_AT,
    expire: values.expiresAt,
    product: {
      productId: "prd_test_123",
      productName: "Local webhook test plan",
    },
    priceDataList: basePriceDataList(),
    metadata: baseMetadata(),
  };
}

function orderFixture(values: {
  status: string;
  paymentTime: number | null;
  paymentExecutionDetails: Record<string, unknown>[];
}): Record<string, unknown> {
  return {
    orderId: "ord_test_123",
    type: "onetime",
    status: values.status,
    merchantReferenceId: "order_test_123",
    sessionId: "sess_test_123",
    customerId: "cus_test_123",
    customerEmail: "test@example.com",
    createTime: ORDER_CREATED_TIME,
    productId: "prd_test_123",
    priceId: "price_test_123",
    priceDataList: basePriceDataList(),
    paymentMethod: {
      paymentMethodType: "CARD",
      paymentInstrumentId: "pi_test_123",
    },
    paymentExecutionDetails: values.paymentExecutionDetails,
    amountSubtotal: 1999,
    amountTotal: 1999,
    paymentCurrency: "USD",
    originalCurrency: "USD",
    paymentTime: values.paymentTime,
    metadata: baseMetadata(),
    riskLevel: "low",
  };
}

function subscriptionFixture(values: {
  status: string;
  activatedAt: string | null;
  pastDueSince: string | null;
}): Record<string, unknown> {
  return {
    object: "subscription",
    subscriptionId: "sub_test_123",
    status: values.status,
    productId: "prd_test_123",
    priceId: "price_test_123",
    customerId: "cus_test_123",
    customer: baseCustomer(),
    currentPeriodStart: CURRENT_PERIOD_START,
    currentPeriodEnd: CURRENT_PERIOD_END,
    cancelAtPeriodEnd: false,
    latestInvoiceId: "inv_test_123",
    createdAt: SUBSCRIPTION_CREATED_AT,
    activatedAt: values.activatedAt,
    pastDueSince: values.pastDueSince,
    metadata: baseMetadata(),
  };
}

function invoiceFixture(values: {
  status: string;
  amountDue: number;
  amountPaid: number;
  paidAt: string | null;
  voidedAt: string | null;
}): Record<string, unknown> {
  return {
    object: "invoice",
    invoiceId: "inv_test_123",
    status: values.status,
    subscriptionId: "sub_test_123",
    customerId: "cus_test_123",
    customer: baseCustomer(),
    amountDue: values.amountDue,
    amountPaid: values.amountPaid,
    currency: "USD",
    dueAt: INVOICE_DUE_AT,
    hostedInvoiceUrl: "https://merchant.example/invoices/inv_test_123",
    lineItems: baseLineItems(),
    createdAt: INVOICE_CREATED_AT,
    paidAt: values.paidAt,
    voidedAt: values.voidedAt,
    metadata: baseMetadata(),
  };
}
